version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres.tjfqvppsaqcfnrueccuv:PiVotN09123@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
      - ENV=production
      - PORT=8000
